#!/bin/bash

# x=1
let x=1

while [ $x -le 10 ]
do
    # x=$(( $x + 1 ))
    let x+=1
    if [ $((x%2)) -eq 0 ]   # if x is even
    then
        # break
        continue
    fi
    echo $x
    sleep 0.2    # or sleep .2
done

echo "Done"

# Note:
    #   - while [ 1 ]
    #   - while [ True ]
    #   - while [ true ]
    #   - while ;
    # all above means while true (infinite loop?)

