#!/bin/bash

# case = switch staement in Java and C++

echo "What is your favorite Ninja Turtle?"
echo "1- Raphael"
echo "2- Leonardo"
echo "3- Michelangelo"
echo "4- Donatello"

read turtle;

case $turtle in
    1)  echo "Raphael is cool, but rood."
        # put any other code here
        # and here
        # and here ...
    ;;
    2)  echo "Leonardo leads.";;
    3)  echo "Michelangelo is the party dude.";;
    4)  echo "Donatello does machines.";;
    *)  echo "Did you even watch the show?";;   # default case
esac